import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading, UserButton } from "@clerk/nextjs";

import {dark} from "@clerk/themes"
import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  return (
    <ClerkProvider appearance={{baseTheme: dark}} >
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              LOADING...
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            
            <div className="max-w-6xl mx-auto">
              <div className="flex flex-col h-screen">
              <div className='bg-cyan-950 rounded-b-xl'>
            <ul className="flex justify-between py-4 px-6">
                <div>
                    <Link href="/">
                    <li>Home</li>
                    </Link>
                </div>
                <div className="flex items-center px=15">
                    <Link href="/client">
                    <li>Client</li>
                        </Link>
                        </div>
                <div className="flex gap-6 items-center">
                  {!userId ?(

                  
                  
                    <>
                    <Link href="/sign-in">
                    <li>login</li>
                    </Link>
                    <Link href="/sign-up">
                    <li>Sign up</li>
                    </Link>
                    </>
                  ):(
                    <>
                    <Link href="/profile">
                    <li>Profile</li></Link>
                    <li className="flex items-center">
                      <UserButton/>
                    </li>
                    </>

                  )}
                   
                
                </div>
            </ul>
        </div>

                {children}
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}


